[package]
name = "crm_action"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
crm_core = { local = "../crm_core" }
crm_data = { local = "../crm_data" }

[addresses]
crm_action = "0x0"
